//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMappingWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public int ID { get; set; }
        public int OBJECTID { get; set; }
        public string ENUMBER { get; set; }
        public string CEQR_NUM { get; set; }
        public string ULURP_NUM { get; set; }
        public Nullable<int> BOROCODE { get; set; }
        public Nullable<int> TAXBLOCK { get; set; }
        public Nullable<int> TAXLOT { get; set; }
        public string ZONING_MAP { get; set; }
        public string DESCRIPTION { get; set; }
        public string BBL { get; set; }
    }
}
