//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMappingWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elevator
    {
        public int ID { get; set; }
        public string job_filing_number { get; set; }
        public string job_number { get; set; }
        public string filing_number { get; set; }
        public Nullable<System.DateTime> filing_date { get; set; }
        public string filing_type { get; set; }
        public string elevatordevicetype { get; set; }
        public string filing_status { get; set; }
        public string filingstatus_or_filingincludes { get; set; }
        public string building_code { get; set; }
        public string electrical_permit_number { get; set; }
        public string bin { get; set; }
        public string house_number { get; set; }
        public string street_name { get; set; }
        public string zip { get; set; }
        public string borough { get; set; }
        public string block { get; set; }
        public string lot { get; set; }
        public string building_type { get; set; }
        public string buildingstories { get; set; }
        public string bbl { get; set; }
    }
}
