//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMappingWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hpd_contacts
    {
        public int ID { get; set; }
        public string RegistrationContactID { get; set; }
        public string RegistrationID { get; set; }
        public string Type { get; set; }
        public string ContactDescription { get; set; }
        public string CorporationName { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string BusinessHouseNumber { get; set; }
        public string BusinessStreetName { get; set; }
        public string BusinessApartment { get; set; }
        public string BusinessCity { get; set; }
        public string BusinessState { get; set; }
        public string BusinessZip { get; set; }
    }
}
