//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMappingWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hpd_business_addresses
    {
        public int ID { get; set; }
        public string businesshousenumber { get; set; }
        public string businessstreetname { get; set; }
        public string businesszip { get; set; }
        public string businessapartment { get; set; }
        public string numberOfContacts { get; set; }
        public string corporationnames { get; set; }
        public string ownernames { get; set; }
        public string uniqregids { get; set; }
    }
}
