//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMappingWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hpd_registrations
    {
        public int ID { get; set; }
        public string RegistrationID { get; set; }
        public string BuildingID { get; set; }
        public string BoroID { get; set; }
        public string Boro { get; set; }
        public string HouseNumber { get; set; }
        public string LowHouseNumber { get; set; }
        public string HighHouseNumber { get; set; }
        public string StreetName { get; set; }
        public string Zip { get; set; }
        public Nullable<int> Block { get; set; }
        public Nullable<int> Lot { get; set; }
        public Nullable<int> BIN { get; set; }
        public Nullable<int> CommunityBoard { get; set; }
        public Nullable<System.DateTime> LastRegistrationDate { get; set; }
        public Nullable<System.DateTime> RegistrationEndDate { get; set; }
        public string bbl { get; set; }
    }
}
