//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMappingWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pluto
    {
        public int OBJECTID { get; set; }
        public string BBL { get; set; }
        public string Borough { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> BldgArea { get; set; }
        public Nullable<int> ComArea { get; set; }
        public Nullable<int> ResArea { get; set; }
        public Nullable<double> NumFloors { get; set; }
        public Nullable<int> UnitsRes { get; set; }
        public string ZoneDist1 { get; set; }
        public string Overlay1 { get; set; }
        public string Overlay2 { get; set; }
        public Nullable<double> AssessTot { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public string OwnerName { get; set; }
        public string BldgClass { get; set; }
        public Nullable<bool> IsRentStabilizedProperty { get; set; }
        public Nullable<int> CD { get; set; }
        public Nullable<int> TractID { get; set; }
    }
}
